admin_news_category:
    pattern:  /news/category
    defaults: { _controller: "NewsBundle:NewsCategory:index" }

admin_news_category_new:
    pattern:  /news/category/new
    defaults: { _controller: "NewsBundle:NewsCategory:new" }

admin_news_category_create:
    pattern:  /news/category/create
    defaults: { _controller: "NewsBundle:NewsCategory:create" }
    requirements: 
       _method: post

admin_news_category_edit:
    pattern:  /news/category/{id}/edit
    defaults: { _controller: "NewsBundle:NewsCategory:edit" }

admin_news_category_update:
    pattern:  /news/category/{id}/update
    defaults: { _controller: "NewsBundle:NewsCategory:update" }
    requirements:
      id:  \d+
      _method: post

admin_news_category_delete:
    pattern:  /news/category/{id}/delete
    defaults: { _controller: "NewsBundle:NewsCategory:delete" }
    requirements: 
      id:  \d+
      _method: post

admin_news_category_change_active:
    pattern:  /news/category/changeActive
    defaults: { _controller: NewsBundle:NewsCategory:changeActive, active: 0 }
  
admin_news_item:
    pattern:  /news/category/{category_id}/item
    defaults: { _controller: "NewsBundle:NewsItem:index" }
    requirements: 
      category_id:  \d+

admin_news_item_new:
    pattern:  /news/category/{category_id}/item/new
    defaults: { _controller: "NewsBundle:NewsItem:new" }
    requirements: 
      category_id:  \d+

admin_news_item_create:
    pattern:  /news/category/{category_id}/item/create
    defaults: { _controller: "NewsBundle:NewsItem:create" }
    requirements: 
      category_id:  \d+
      _method: post

admin_news_item_edit:
    pattern:  /news/category/{category_id}/item/{id}/edit
    defaults: { _controller: "NewsBundle:NewsItem:edit" }
    requirements: 
      category_id:  \d+
      id:  \d+

admin_news_item_update:
    pattern:  /news/category/{category_id}/item/{id}/update
    defaults: { _controller: "NewsBundle:NewsItem:update" }
    requirements:
      category_id:  \d+
      id:  \d+
      _method: post

admin_news_item_delete:
    pattern:  /news/category/{category_id}/item/{id}/delete
    defaults: { _controller: "NewsBundle:NewsItem:delete" }
    requirements:
      category_id:  \d+
      id:  \d+
      _method: post
    
admin_news_item_change_active:
    pattern:  /news/item/changeActive
    defaults: { _controller: NewsBundle:NewsItem:changeActive, active: 0 }