parameters:
#    wifinder_news.example.class: Wifinder\NewsBundle\Example

services:
#    wifinder_news.example:
#        class: %wifinder_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
